apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: piomin/sample-spring-kotlin-microservice
    jib:
      args:
        - -Pjib,tomcat
        - -DskipTests
  tagPolicy:
    gitCommit: {}
